interface ZIF_G_BOOKING_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112B0575',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112B8575',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112A4575',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112C0575',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112A8575',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112B4575',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '005056044E851EEC9CF8CD3C112BC575',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C112A2575',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C1129E575',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C112AE575',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C112C6575',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C112C4575',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEC9CF8CD3C112C8575',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EEC9CF8CD3C11294575' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZG_BOOKING' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9CF8CD3C11298575',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9CF8CD3C112A0575',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9CF8CD3C1129C575',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEC9CF8CD3C112AC575',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EEC9CF8CD3C1129A575',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 SELECT_ALL                     TYPE /BOBF/OBM_QUERY_KEY VALUE '005056044E851EEC9CF8CD7D0DFCC576',
 SELECT_BY_ELEMENTS             TYPE /BOBF/OBM_QUERY_KEY VALUE '005056044E851EEC9CF8CD7D0DFDA576',
      END OF ROOT,
    END OF SC_QUERY .
endinterface.
